# fly.toml app configuration file generated for spark-rewards on 2024-08-29T08:00:20+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spark-rewards'
primary_region = 'cdg'

[env]
  SENTRY_ENVIRONMENT = "production"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/scheduled-rewards/0x802720eeca89AD84b2d91c71f9Dc29052574769E"

[[vm]]
  size = 'shared-cpu-4x'
  memory = '2048mb'
